SpiNNakerManchester/sPyNNaker8

- spynnaker8/spinnaker.py
create_population and create_projection are not used by
sPyNNaker8 due to the change in the Population and Projection
methods between pynn0.7 and pynn0.8
> Update to add required methods to SpiNNaker class

- spynnaker8/__init__.py
Fix for SpiNNakerManchester/sPyNNaker#372
Removes the exit function that doesn't exist in pyNN 0.7 (seems to have come from Jamie's code).
> Remove the exit function as it can cause issues (not done in pyNN 0.7)

- spynnaker8/__init__.py
gives us a 5.4 times speed up on simple synfire chain. likely to give more for larger sims. 
depends upon the following prs:
Note that this work is not finished, but is stable. Future work will come which will increase this even further
> Speed up data extractor

- spynnaker8/models/populations/population.py
- unittests/test_using_virtual_baord/test_celltype.py
As the DataHolder does http://neuralensemble.org/docs/PyNN/reference/neuronmodels.html
celltype should return the DataHolder
> Changed Celltype to return DataHolder

- p8_integration_tests/test_array_connector/test_array_connector.py
Added another population to the integration test where only the even-numbered neurons are connected in a synfire chain.  It might be worth adding further to this with a non-uniform array of connections, I'm not sure... open to suggestions.
Depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/496
> Update integration test for ArrayConnector

- spynnaker8/models/recorder.py
- spynnaker8/utilities/neo_convertor.py
Thanks @SimonDavidson good spot.
The spike source array returns spikes as a list.
If there are no spikes an empty list is only 1 dimensional unlike the np.array size (0,2)  returned by neurone_recorder
Also fix for neo converter as like the recorder numpy does not like empty lists.
> improved handling of cases with zero spikes,

- requirements-test.txt
Travis was complaining about the pytest version after the latest merge to master I did, so I've updated it.
> update pytest to version required for timeout

- p8_integration_tests/test_if_curr_exp_live_buffers/test_synfire_if_curr_exp.py
Been looking at integration tests for the synapse_expander_on_chip branch, discovered this one that was being skipped, but it now works (with the correct size for the spikes array).  I think the reason it was being skipped was fixed a while ago...
> No skip, and fix value in integration test

- spynnaker8/external_devices/__init__.py
Missed this during the changes to the neuron models - this is required to make the pushbot-over-ethernet work correctly again.
> Fix injector params

- spynnaker8/__init__.py
Fixing https://github.com/SpiNNakerManchester/sPyNNaker/issues/147 - open to opinions over whether we need a named constant for this conversion, as we do perform similar conversions elsewhere in this repository and the sPyNNaker repository.
> get_time_step should return ms, not microseconds

- p8_integration_tests/long_test/test_big_connection/test_java_advanced/spynnaker.cfg
- p8_integration_tests/long_test/test_big_connection/test_java_advanced/test_big_connection.py
- p8_integration_tests/long_test/test_big_connection/test_java_simple/spynnaker.cfg
- p8_integration_tests/long_test/test_big_connection/test_java_simple/test_big_connection.py
- p8_integration_tests/long_test/test_big_connection/test_python_advanced/spynnaker.cfg
- p8_integration_tests/long_test/test_big_connection/test_python_advanced/test_big_connection.py
- p8_integration_tests/long_test/test_big_connection/test_python_simple/spynnaker.cfg
- p8_integration_tests/long_test/test_big_connection/test_python_simple/test_big_connection.py
Arrange for the big connection test to run with and without advanced monitors, and with and without Java. This is a test for which it makes sense; it exercises Data In relatively well (though for a single board).
Initial performance measurements indicate that things go about twice as fast when producing big input for a single board, comparing traditional (Python, pure SCP) to the fastest option (Java, Fast Data In). That's nice.
> Make the big connection test run in multiple configurations

- spynnaker8/spinnaker.py
Fix a minor annoyance that the start message was wrong because dt was in microseconds.
> Fix start message

- unittests/test_integration_using_virtual_board/test_if_curr_alpha.py
The fix last week at https://github.com/SpiNNakerManchester/sPyNNaker/pull/748 uncovered an error in one of the sPyNNaker8 unit tests.
> Delay in script too large, caught by sPyNNaker fix last week

- spynnaker8/__init__.py
Fix that allows PyNN timestep, min_delay and max_delay in setup call to have the value "auto".
> Fix for PyNN changes

- p8_integration_tests/quick_test/test_various/test_synaptic_expander.py
The test as it stood sporadically failed; simply adding a fixed seed makes sure it passes correctly.
> Update test to use fixed seed to avoid sporadic failures

- p8_integration_tests/quick_test/test_grid_based_connectors/test_small_world_connector.py
- p8_integration_tests/scripts_test/test_microcircuit.py
test_microcircuit has been failing on the overnight cron job testing because there was no check as to whether the results directory existed already.
> Fix failing microcircuit test

- Jenkinsfile.cron
- p8_integration_tests/quick_test/test_connectors/test_connectors.py
- p8_integration_tests/scripts_test/build_script.py
Removes from pr test the script that took over 100 seconds to run each
Note: Longer scripts and the microcircuit are still in the crom job
This will reduce each test run by about 30 minutes
> skip examples which take over 100 seconds

- p8_integration_tests/quick_test/test_connectors/test_connectors.py
Adding a multi-core test with PopulationViews for the OneToOneConnector, testing fix at https://github.com/SpiNNakerManchester/sPyNNaker/pull/779
> Add multi-core test for OneToOne when using PopulationViews

- p8_integration_tests/quick_test/test_grid_based_connectors/test_small_world_connector.py
- spynnaker8/models/connectors/small_world_connector.py
Update occasionally failing test to use seeded RNG (which required updating the argument list, which may clash with some of the doc-changes... ?).
> Update test to use seeded rng which should mean no occasional failures

- p8_integration_tests/scripts_test/build_script.py
On quick tests only
Skip balanced_random_live_rate.py as it takes 125 seconds
Skip vogels_2011.py as it takes 698 seconds
Assume all scripts now work.except sudoku.py and pushbot_ethernet_example.py which need external stuff the testers just do not have.
> skip 2 long examples

- spynnaker8/__init__.py
We already allowed setup to be called twice
This cleared the previous run and before creating a new simulator
This now makes it even more rebost to failure.
Note this continues to have the same effect as doing a simulator.end
Reusing any object created with a previous sim.setup will cause weird errors. (with or without end)
> more agggressive cleanup on second setup

- p8_integration_tests/base_test_case.py
- p8_integration_tests/quick_test/test_power_monitoring/__init__.py
- p8_integration_tests/quick_test/test_power_monitoring/spynnaker.cfg
- p8_integration_tests/quick_test/test_power_monitoring/test_power_mon.py
This does testing for SpiNNakerManchester/SpiNNFrontEndCommon#569
The test check that, when the right options are selected in the config file, we:
1. generate a power usage report, and
2. add power provenance information to the provenance output (in DB form).
The test does _not_ check that the power information is itself correct. However, it looks OK when I eyeball it.
> Power provenance testing

- Jenkinsfile
Most recent pytest-xdist (2.0.0) has an error at the moment (see https://github.com/SpiNNakerManchester/sPyNNaker8/issues/434).  Fixing for now by going back to older version.
> Bypass problem with pytest-xdist 2.0.0 for now

- p8_integration_tests/quick_test/test_ignores/spynnaker.cfg
Adds repair_machine=True to one of the tests, required now that things have changed.
> Add Link to Info
