- spynnaker8/spynnaker8.cfg
fixes issue with virutal board mapping algorithms
> fix virtual board mapping algorithms

- p8_integration_tests/backwards_compatibility_issues/ssa.py
- spynnaker8/models/populations/population.py
> fix issue with backwards compability

- spynnaker8/models/populations/population.py
title
depends upon spynnaker (https://github.com/SpiNNakerManchester/sPyNNaker/pull/325)
> fixes recording reset to reset instead of turning off recording

- spynnaker8/utilities/data_holder.py
- unittests/parameters_test.py
as required by:
http://neuralensemble.org/docs/PyNN/neurons.html
> added default_parameters and get_parameter_names()

- spynnaker8/__init__.py
- spynnaker8/models/populations/population.py
- unittests/test_list_standard_models.py
- unittests/test_using_virtual_baord/spynnaker.cfg
- unittests/test_using_virtual_baord/test_celltype.py
Adds or fixes a few minor things required by PyNN8
> List standard modules

- spynnaker8/models/recorder.py
[This commit](https://github.com/SpiNNakerManchester/sPyNNaker/pull/334) broke the build in this repo. This PR fixes it.
> Changes due to upstream modifications.

- spynnaker8/spinnaker.py
Also requires pull in spynakker
> moved run fix to correct place

- spynnaker8/models/recorder.py
Where list objects changed to orderset the list methods have to be changed to set ones
> replaced append to add

- spynnaker8/setup-pynn.py
Although we want PyNN to include these links eventually, having a script we can point users at does no harm
> Migrated setup script

- spynnaker8/models/projection.py
SpyNNaker 8 Changes for the changes in sPyNNaker
> Fix connection holder pynn 8

- p8_integration_tests/test_iobuf/test_iobuf_without_during_run_flag/spynnaker.cfg
- p8_integration_tests/test_iobuf/test_iobuf_without_during_run_flag/test_synfire_if_curr_exp.py
fixes issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/284
linked to https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/172
> Fix iobuf extract at end

- p8_integration_tests/test_remote_spinnaker/va_benchmark.py
- spynnaker8/__init__.py
- spynnaker8/external_devices/__init__.py
fixed issue https://github.com/SpiNNakerManchester/sPyNNaker8/issues/37
> fix issue #37

- spynnaker8/__init__.py
- spynnaker8/models/connectors/__init__.py
fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/250
> fix for #250

- setup.py
- spynnaker8/spinnaker.py
> Add front end provenance

- requirements.txt
- setup.py
Bumped version as quantities 12.0 version was broken
removed github install
> Quantities bumped to 0.12.1

- spynnaker8/utilities/random_stats/random_stats_binomial_impl.py
- spynnaker8/utilities/random_stats/random_stats_exponential_impl.py
- spynnaker8/utilities/random_stats/random_stats_gamma_impl.py
- spynnaker8/utilities/random_stats/random_stats_log_normal_impl.py
- spynnaker8/utilities/random_stats/random_stats_normal_clipped_impl.py
- spynnaker8/utilities/random_stats/random_stats_normal_impl.py
- spynnaker8/utilities/random_stats/random_stats_poisson_impl.py
- spynnaker8/utilities/random_stats/random_stats_randint_impl.py
- spynnaker8/utilities/random_stats/random_stats_scipy_impl.py
- spynnaker8/utilities/random_stats/random_stats_uniform_impl.py
- spynnaker8/utilities/random_stats/random_stats_vonmises_impl.py
All three pull request must be done at the same time!
> Use AbstractRandomStats for high and low vs boundaries refactor

- spynnaker8/spinnaker.py
> Fixes current time to actually be the current time

- spynnaker8/models/populations/population.py
- there's probably also a way of doing this with neo objects which
should be investigated
Related to issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/414
> Add get_spike_counts to population

- p8_integration_tests/test_from_file_connector/test_from_file_connector.py
- spynnaker8/models/connectors/from_file_connector.py
Fix of issue https://github.com/SpiNNakerManchester/sPyNNaker8/issues/78
> FromFileConnector: add missing method

- p8_integration_tests/test_if_curr_exp_live_buffers/spynnaker.cfg
- p8_integration_tests/test_if_curr_exp_live_buffers/test_synfire_if_curr_exp.py
This enables the test that was broken, and thus fixes SpiNNakerManchester/SpiNNFrontEndCommon#162.
> Fix buffered out

- p8_integration_tests/test_external_devices/spynnaker.cfg
- p8_integration_tests/test_external_devices/test_recordable_spike_injector.py
> Added a test for recordable spike injection

- spynnaker8/models/populations/population.py
Depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/418
> check population size is int or roundable to int

- spynnaker8/models/data_cache.py
- spynnaker8/models/recorder.py
As there can be different sampling intervals, I will later get it from the data.
depends on: https://github.com/SpiNNakerManchester/sPyNNaker/pull/442
> removed shared sampling interval

- spynnaker8/spynnaker_plotting.py
Oops that was clearly never tested.
> fixed len bug

- p8_integration_tests/test_fixed_number_connectors/test_fixed_number_post_connector.py
- p8_integration_tests/test_fixed_number_connectors/test_fixed_number_pre_connector.py
- p8_integration_tests/test_fixed_number_connectors/test_larger_fixed_number_post_connector.py
- p8_integration_tests/test_fixed_number_connectors/test_larger_fixed_number_pre_connector.py
- spynnaker8/models/connectors/fixed_number_post_connector.py
- spynnaker8/models/connectors/fixed_number_pre_connector.py
Tests and associated minor changes for fixing fixed-number connectors, see issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/435
Depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/441.
> Fixed number connectors

- p8_integration_tests/test_stdp/test_STDP_nearest_pair_additive.py
- p8_integration_tests/test_stdp/test_STDP_pair_additive.py
- spynnaker8/__init__.py
- spynnaker8/extra_models/__init__.py
Update to spynnaker8 __init__, and tests of nearest-pair-additive and all-pairs-additive STDP rules
> Nearest pair timing stdp unit test

- spynnaker8/models/data_cache.py
> Make cache local to data_cache object

- spynnaker8/__init__.py
This fixes some of the Sphinx errors in our builds caused by infelicities in PyNN classes and functions that we (used to) directly re-expose.
The `list-table` directive is nice.
> Documentation fix

- p8_integration_tests/test_array_connector/test_array_connector.py
- spynnaker8/models/connectors/array_connector.py
Wrapper for the sPyNNaker ArrayConnector and an associated integration test to go with it.
Depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/494
> Array connector

- p8_integration_tests/test_stdp/test_IF_cond_exp_stdp_mad_pair_additive.py
Test for one of the neuron/STDP models used in Petrut's paper
> Add test for IF_cond_exp_stdp_mad_pair_additive

- p8_integration_tests/test_0_1_time_steps/test_gsyn_allow_violate/test_synfire_0dot1_timestep_test_print_gsyn.py
- p8_integration_tests/test_0_1_time_steps/test_malloc_key_allocator/test_synfire_if_curr_exp_with_malloc_key_allocator.py
- p8_integration_tests/test_0_1_time_steps/test_spikes/test_synfire_0dot1_timestep_test_print_spikes.py
- p8_integration_tests/test_0_1_time_steps/test_v/test_synfire_0dot1_timestep_test_print_v.py
- p8_integration_tests/test_0_1_time_steps/test_va_bench_mark_tests/test_va_benchmark.py
- p8_integration_tests/test_1_0_time_steps/test_gsyn/test_synfire_1dot0_timestep_test_print_gsyn.py
- p8_integration_tests/test_1_0_time_steps/test_malloc_key_allocator/test_synfire_if_curr_exp_with_malloc_key_allocator.py
- p8_integration_tests/test_1_0_time_steps/test_spikes/test_synfire_1dot0_timestep_test_print_spikes.py
- p8_integration_tests/test_1_0_time_steps/test_v/test_synfire_1dot0_timestep_test_get_v.py
- p8_integration_tests/test_1_0_time_steps/test_v/test_synfire_1dot0_timestep_test_print_v.py
- p8_integration_tests/test_1_0_time_steps/test_va_bench_mark_tests/test_va_benchmark.py
https://github.com/NeuralEnsemble/python-neo/issues/529
> Neo pickle bug skip the tests that fail because of it.

- p8_integration_tests/test_array_connector/test_array_connector.py
- p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_200n_100pc_with_delays_all_recording.py
- p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_delay_extensions_all_recording.py
- p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_no_delay_extension_all_recording.py
- p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_no_delays_all_recording.py
- p8_integration_tests/test_report_generation/test_speed_up_report_generation.py
not going to discover why v changed ever so minorly
> Test tolerance

- p8_integration_tests/test_array_connector/test_array_connector.py
- p8_integration_tests/test_spinnaker_link_connectors/requires_virtual_board/test_spinnaker_link_2_different_boards_no_board_address.py
- p8_integration_tests/test_spinnaker_link_connectors/requires_virtual_board/test_spinnaker_link_2_different_boards_valid_board_address.py
The size of the external_devices.ExternalFPGARetinaDevice appears to have changed.
If correct tests needed to be changed.
If not close PR and open an issue.
> Retina device size change (Is this correct?)

- spynnaker8/setup_pynn.py
Fix for https://github.com/SpiNNakerManchester/sPyNNaker8/issues/161
> fix to make version check work with pynn 0.9.0

- p8_integration_tests/test_various/test_spike_io_multi_run.py
... committed previous change to master in error, this fixes the flake8 error on that.
> SpikeIO multi run now works

- p8_integration_tests/test_change_neuron_parameters_between_runs/test_change_parameter.py
- p8_integration_tests/test_change_neuron_parameters_between_runs/test_change_spike_source_poisson.py
Updated integration tests whilst I was testing them out in conjunction with change at https://github.com/SpiNNakerManchester/sPyNNaker/pull/557 - found a broken one and one that was being skipped but is now working, so issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/423 may also be fixed now.
> While fixing a bug, updated some tests

- p8_integration_tests/test_change_neuron_parameters_between_runs/test_set_toffset_izk.py
- p8_integration_tests/test_current_calculation/test_cond_vs_current_vs_izk.py
- p8_integration_tests/test_various/test_synfire_Izhikevich.py
- fix other Izhikevich integration tests to match API
> Add integration test for run-set-run with Izhikevich

- p8_integration_tests/test_selective_recording/test_thritytwo.py
Test for https://github.com/SpiNNakerManchester/sPyNNaker/pull/571
Will fail until above pull request merged,
> test for bug 32

- p8_integration_tests/test_external_devices/test_recordable_spike_injector.py
- setup.py
https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75
> Deprication wanrings

- spynnaker8/models/populations/population.py
avoid the confusing misuse like:
import spynnaker8 as sim
sim.setup(1.0)
cell_params_lif = {'cm': 0.25}
pop_1 = sim.Population(5, sim.IF_curr_exp(), cell_params_lif, label="pop_1")
sim.run(1)
print(pop_1.get("cm"))
print(cell_params_lif)
sim.end()
> Pop is cellparams are being ignored.

- p8_integration_tests/quick_test/test_without_extra_monitor/spynnnaker.cfg
- p8_integration_tests/quick_test/test_without_extra_monitor/test_simple_script.py
Adds a test for SpiNNakerManchester/SpiNNFrontEndCommon#429
> Fix sdram allocations

- p8_integration_tests/quick_test/test_various/test_synaptic_expander.py
- spynnaker8/__init__.py
Part of SpiNNakerManchester/sPyNNaker#649.  This mainly adds a test for all the synaptic expander parts.
> Fix synapse expander

- spynnaker8/models/populations/population.py
Added as requested in https://github.com/SpiNNakerManchester/sPyNNaker/issues/452 as this is still in pyNN 0.9.
> Add tset function (deprecated, but still in pyNN 0.9 API)

- spynnaker8/models/projection.py
> Use labels given to projection in description rather than edge labels

- requirements.txt
- setup.py
part of https://github.com/SpiNNakerManchester/sPyNNaker/pull/678
> exclude csa to fix  readthedocs

- p8_integration_tests/base_test_case.py
prints a few info lies when it goes to try a test again
> print on retry

- Jenkinsfile
- setup.py
https://github.com/SpiNNakerManchester/SpiNNStorageHandlers/pull/35
> Delete unused files in SpiNNStorageHandlers

- p8_integration_tests/scripts/manyBoards.py
- spynnaker8/__init__.py
- spynnaker8/spinnaker.py
part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/474
> sim setup with n_boards

- spynnaker8/external_devices/__init__.py
Matching changes to SpiNNakerManchester/sPyNNaker#699
> Fix Ethernet Control Connection

- Jenkinsfile
- p8_integration_tests/base_test_case.py
- p8_integration_tests/quick_test/test_external_devices/test_multiboard_spike_output.py
Testing changes to the LEC DB code in FEC
> Don't disable parallel testing

- spynnaker8/models/populations/population.py
- unittests/test_pop_views_assembly/test_views.py
For some reason, it was only defined for `PopulationView`.
> Add `sample()` method to `Population`

- Jenkinsfile
- Jenkinsfile.cron
- p8_integration_tests/test_new_model_templates/test_new_model_templates.py
runs sPyNNaker8NewModelTemplate/examples
and runs
https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/41
> test new model templates

- README.md
- p8_integration_tests/quick_test/test_external_devices/test_recordable_spike_injector.py
- spynnaker8/spinnaker.py
Part of SpiNNakerManchester/SpiNNFrontEndCommon#472
>  avoid_duplicate_info test

- p8_integration_tests/quick_test/test_onchip_compressor/many_routes.py
- p8_integration_tests/quick_test/test_onchip_compressor/test_mundy/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_mundy/test_mundy_compressor.py
- p8_integration_tests/quick_test/test_onchip_compressor/test_pair/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_pair/test_pair_compressor.py
Tests for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/465
> test compressors

- p8_integration_tests/quick_test/test_external_devices/test_recordable_spike_injector.py
- setup.py
https://github.com/SpiNNakerManchester/SpiNNUtils/issues/102
> fixed incorrect import from collections.abc

- p8_integration_tests/long_test/test_long_recording/__init__.py
- p8_integration_tests/long_test/test_long_recording/test_java_advanced/__init__.py
- p8_integration_tests/long_test/test_long_recording/test_java_advanced/spynnaker.cfg
- p8_integration_tests/long_test/test_long_recording/test_java_advanced/test_multi_blob_recording.py
- p8_integration_tests/long_test/test_long_recording/test_python_advanced/__init__.py
- p8_integration_tests/long_test/test_long_recording/test_python_advanced/test_multi_blob_recording.py
Tests using both Java and Python doing the downloading. (These tests are quick enough now that they could go in the quick tests.)
See SpiNNakerManchester/SpiNNFrontEndCommon#496
> Tests for BLOB handling with multiple BLOBs in play

- p8_integration_tests/quick_test/test_external_devices/test_live_neuron_voltage.py
- p8_integration_tests/quick_test/test_spike_source/test_poisson_spike_source.py
- spynnaker8/external_devices/__init__.py
Add integration test for live poisson.
> Fix Poisson Sender

- unittests/mocks.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/501
Fixes https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/499
> prefix never used so NUKE!

- spynnaker8/models/populations/population.py
- spynnaker8/models/populations/population_base.py
- spynnaker8/models/populations/population_view.py
Addresses https://github.com/SpiNNakerManchester/sPyNNaker8/issues/288
Added Annotations to all data retrieve methods are then just some and I feel here PyNN is wrong.
> annotations on all rather than just some

- p8_integration_tests/test_new_model_templates/test_new_model_templates.py
Companion for https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/44
> Add "old" sEMD example to NMT tests

- p8_integration_tests/quick_test/test_connectors/test_all_to_all_connector.py
- p8_integration_tests/quick_test/test_connectors/test_connectors.py
- spynnaker8/models/connectors/fixed_probability_connector.py
- spynnaker8/models/populations/population_view.py
- spynnaker8/models/projection.py
Reverts #292.
Revering due to issues. Will create a PR to bring back in in a minute...
> Revert "Projections on popviews"

- spynnaker8/utilities/neo_convertor.py
Adds testing and new model template example.
depends on 
https://github.com/SpiNNakerManchester/sPyNNaker/pull/716
https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/42
All three must be done at the same time.
When approved nuke:
https://github.com/SpiNNakerManchester/DataSpecification/tree/neuron_recorder2
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/tree/neuron_recorder2
> Neuron recorder2

- p8_integration_tests/quick_test/test_spike_source/test_spike_source_array.py
Accompanying test for https://github.com/SpiNNakerManchester/sPyNNaker/pull/729
> Add SSA test with recording and empty lists on cores

- README.md
- p8_integration_tests/base_test_case.py
- p8_integration_tests/quick_test/test_iobuf/test_cores_and_binaries_recorded/test_cores_and_binaries_recording.py
- p8_integration_tests/quick_test/test_iobuf/test_iobuf_without_during_run_flag/test_noIobuf_during_run.py
- p8_integration_tests/quick_test/test_iobuf/test_multirun/test_multirun_with.py
- p8_integration_tests/quick_test/test_iobuf/test_only_binaries_recorded/test_only_binaries_recording.py
- p8_integration_tests/quick_test/test_iobuf/test_only_cores_recorded/test_only_core_recording.py
> Jenkins for app folder vs system folder

- p8_integration_tests/quick_test/test_connectors/test_all_to_all_connector.py
- p8_integration_tests/quick_test/test_connectors/test_connectors.py
- p8_integration_tests/quick_test/test_reuse_connector/test_reuse_connector_different_pops.py
- p8_integration_tests/quick_test/test_various/test_synaptic_expander.py
- spynnaker8/models/connectors/fixed_probability_connector.py
- spynnaker8/models/populations/population_view.py
- spynnaker8/models/projection.py
- unittests/mocks.py
- unittests/test_from_file_connector.py
Bringing back projections on pop views to be fixed. Don't merge until new test has been added (test to be determined).
Depends on SpiNNakerManchester/sPyNNaker#723
> Projections on popviews (again)

- spynnaker8/models/populations/idmixin.py
- spynnaker8/models/recorder.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker8/issues/310
And now allows recording on idmixin/ views of size 1
> View recording fix

- spynnaker8/__init__.py
- spynnaker8/spinnaker.py
fixed double conversion from micro to milli seconds
Fixes: https://github.com/SpiNNakerManchester/sPyNNaker8/issues/313
> fixed micro milli double conversion

- spynnaker8/spinnaker.py
Moves a log to AbstractsPyNNkerBase 
See https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/525
> moved run message to AbstractSpinnakerBase

- spynnaker8/models/projection.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker8/issues/319
> Make projection.save(...) work for 'all' and 'connections'

- Jenkinsfile
due to https://github.com/nedbat/coveragepy/issues/883
> coverage version capped 

- spynnaker8/models/populations/population.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker8/issues/331
Depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/765
> Read parameters from machine prior to set

- p8_integration_tests/quick_test/test_connectors/test_one_to_one_connector.py
Add some tests for 1:1 connector.
Depends on SpiNNakerManchester/sPyNNaker#773
> Fix one to one generator

- p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_200n_100pc_with_delays_all_recording.py
- spynnaker8/__init__.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker8/issues/328
Depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/764 (to some extent)
Examples modified in https://github.com/SpiNNakerManchester/PyNN8Examples/pull/33
> Expose IF_curr_delta as a standard PyNN model

- p8_integration_tests/quick_test/test_connectors/test_kernel_connector.py
- spynnaker8/models/connectors/kernel_connector.py
Depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/785
> Rename kernel parameters for starts & steps to be less confusing

- p8_integration_tests/quick_test/test_various/test_alltoone_with_large_weight.py
Test for https://github.com/SpiNNakerManchester/sPyNNaker/pull/740
> Test for large weights bug fix

- p8_integration_tests/quick_test/test_various/test_reset_clears_delayed_spike.py
Test for https://github.com/SpiNNakerManchester/sPyNNaker/pull/793
> Clear on reset fix

- README.md
- p8_integration_tests/quick_test/test_debug_mode/check_debug.py
Test for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/554
> donal_fec_changes

- Jenkinsfile
- p8_integration_tests/base_test_case.py
- p8_integration_tests/scripts_test/build_script.py
Try running them in parallel so I can fix what goes wrong...
> Parallel examples

- README.md
- p8_integration_tests/quick_test/test_struct_pl/test_structural_shared.py
- p8_integration_tests/quick_test/test_struct_pl/test_structural_with_stdp.py
Running integration tests for https://github.com/SpiNNakerManchester/sPyNNaker/pull/809
> Jenkins commit

- p8_integration_tests/quick_test/test_various/test_params_using_random_dists.py
Add new test with each possible distribution used for the neuron parameters.
Merge with https://github.com/SpiNNakerManchester/DataSpecification/pull/84
and https://github.com/SpiNNakerManchester/sPyNNaker/pull/810
> Add test to check that RandomDistributions work for each possible dist

- p8_integration_tests/quick_test/test_struct_pl/test_structural_elimination_to_empty.py
- p8_integration_tests/quick_test/test_struct_pl/test_structural_formation_to_full.py
Integration tests for https://github.com/SpiNNakerManchester/sPyNNaker/pull/808
> Add integration tests for struct plasticity full formation / elimination

- p8_integration_tests/quick_test/test_various/test_multi_step.py
Testing of SpiNNakerManchester/sPyNNaker#817
Adds a test.
> Multi-time-step testing

- .travis.yml
- p8_integration_tests/scripts_test/script_checker.py
- pynn9_neo5_changes.md
this fixes issues with new flake8
> Fix jenkins

- p8_integration_tests/quick_test/test_connectors/test_fixed_number_post_connector.py
Adding test related to https://github.com/SpiNNakerManchester/sPyNNaker/pull/821
> Test to check connection estimates are working

- p8_integration_tests/quick_test/test_change_neuron_parameters_between_runs/test_set_initial_value.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker8/issues/331
(when merged with https://github.com/SpiNNakerManchester/sPyNNaker/pull/825).
> Add test for set_initial_value between runs

- p8_integration_tests/quick_test/test_onchip_compressor/test_pair/test_pair_compressor.py
check https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/618 is resolved
> check pair compressor

- p8_integration_tests/quick_test/test_onchip_compressor/test_bit_field/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_pair_bit_field/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_pair_bit_field/test_pair_bit_field_compressor.py
- p8_integration_tests/quick_test/test_onchip_compressor/test_unordered/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_unordered/test_unordered_compressor.py
- p8_integration_tests/quick_test/test_onchip_compressor/test_unordered_bit_field/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_unordered_bit_field/test_bit_field_compressor.py
Adds test for the various compressors in https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/631
> more compressor testing

- spynnaker8/models/populations/population.py
Tests for SpiNNakerManchester/sPyNNaker#853
> Testing of remove_gnu_functions

- .travis.yml
- Jenkinsfile
- Jenkinsfile.cron
- setup.py
- spynnaker8/models/populations/population.py
Also run each version with best choice of Ubuntu distribution
> Add testing with Python 3.8

- Jenkinsfile
- Jenkinsfile.cron
See https://github.com/pypa/setuptools/issues/2350.
> Broken setuptools for now

- README.md
- spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_static.py
- spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_stdp.py
removed rename in import
Part of https://github.com/SpiNNakerManchester/sPyNNaker/pull/872
> Nuke common

- Jenkinsfile
- Jenkinsfile.cron
- README.md
Depends on https://github.com/SpiNNakerManchester/SpiNNUtils/pull/121
See the reports section of the Jenkins run.
> Log binaries

- spynnaker8/models/recorder.py
dont you even dare making masses of branches!
> fixy fixy for andy. you better not be smart now pycharm!

- README.md
- unittests/test_from_file_connector.py
test for https://github.com/SpiNNakerManchester/sPyNNaker/pull/887
> Slice index is not vertex index 

- README.md
- unittests/test_from_file_connector.py
Tests https://github.com/SpiNNakerManchester/sPyNNaker/pull/888
> jenkins trigger for Edge saves slices 

- .travis.yml
- Jenkinsfile
- Jenkinsfile.cron
- doc/doc_requirements.txt
- doc/source/conf.py
- pypi_to_import
- requirements.txt
- setup.py
Purging the use of SpiNNStorageHandlers; the value of that repo is now zero.
See https://github.com/SpiNNakerManchester/SpiNNMan/pull/221
> No more storage handlers

- spynnaker8/models/recorder.py
> Eprop incremental graph

- p8_integration_tests/quick_test/test_master_pop/__init__.py
- p8_integration_tests/quick_test/test_master_pop/algorithms.xml
- p8_integration_tests/quick_test/test_master_pop/key_constraint_adder.py
- p8_integration_tests/quick_test/test_master_pop/spynnaker.cfg
- p8_integration_tests/quick_test/test_master_pop/test_master_pop_merging_with_pop_and_delays_mergable.py
this exposes the bug in the pop based master pop for master for merging.
> failed test

- p8_integration_tests/base_test_case.py
- p8_integration_tests/quick_test/test_stdp/test_STDP_nearest_pair_multiplicative.py
- p8_integration_tests/quick_test/test_stdp/test_STDP_pair_multiplicative.py
Added some simple tests (and comparisons to exact answers) for STDP with multiplicative weight dependence.  Part of fixing https://github.com/SpiNNakerManchester/sPyNNaker8/issues/484.
> Add tests for STDP with multiplicative weight dependence

- p8_integration_tests/quick_test/test_stdp/test_IF_cond_exp_stdp_nearest_pair_additive.py
Another test of a binary previously untested (see https://github.com/SpiNNakerManchester/sPyNNaker8/issues/484).
> Add a test for nearest-pair STDP rule with conductance neuron model

- .github/workflows/python_actions.yml
- requirements-test.txt
Builds on https://github.com/SpiNNakerManchester/sPyNNaker8/pull/490
> Python actions with sphinx

- p8_integration_tests/quick_test/test_external_devices/test_live_sync.py
- spynnaker8/external_devices/__init__.py
- spynnaker8/spinnaker.py
Adds calls to make it possible to use the functionality in SpiNNakerManchester/SpiNNFrontEndCommon#666.  Also adds a test of this functionality.
> Run synchronized

- README.md
- setup.py
part of https://github.com/SpiNNakerManchester/sPyNNaker/pull/957
> upgrade neo

- LICENSE.md
- unittests/test_pop_views_assembly/test_models.py
new tests
tests: https://github.com/SpiNNakerManchester/sPyNNaker/pull/972
> jenkins and extra tests!
